# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\param_dread_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParamDreadWindow(object):
    def setupUi(self, ParamDreadWindow):
        ParamDreadWindow.setObjectName("ParamDreadWindow")
        ParamDreadWindow.resize(1395, 733)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/698/698.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/698/698.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        ParamDreadWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ParamDreadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_28.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_28.setSpacing(6)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_10.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_25.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_155 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_155.setSpacing(6)
        self.horizontalLayout_155.setObjectName("horizontalLayout_155")
        self.label_156 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_156.sizePolicy().hasHeightForWidth())
        self.label_156.setSizePolicy(sizePolicy)
        self.label_156.setMinimumSize(QtCore.QSize(110, 0))
        self.label_156.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_156.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_156.setObjectName("label_156")
        self.horizontalLayout_155.addWidget(self.label_156)
        self.esam_no_box_7 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_no_box_7.sizePolicy().hasHeightForWidth())
        self.esam_no_box_7.setSizePolicy(sizePolicy)
        self.esam_no_box_7.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_no_box_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_no_box_7.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_no_box_7.setBaseSize(QtCore.QSize(150, 0))
        self.esam_no_box_7.setText("")
        self.esam_no_box_7.setMaxLength(12)
        self.esam_no_box_7.setObjectName("esam_no_box_7")
        self.horizontalLayout_155.addWidget(self.esam_no_box_7)
        self.verticalLayout_25.addLayout(self.horizontalLayout_155)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_146 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_146.sizePolicy().hasHeightForWidth())
        self.label_146.setSizePolicy(sizePolicy)
        self.label_146.setMinimumSize(QtCore.QSize(110, 0))
        self.label_146.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_146.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_146.setObjectName("label_146")
        self.horizontalLayout_3.addWidget(self.label_146)
        self.esam_no_box_2 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_no_box_2.sizePolicy().hasHeightForWidth())
        self.esam_no_box_2.setSizePolicy(sizePolicy)
        self.esam_no_box_2.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_no_box_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_no_box_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_no_box_2.setBaseSize(QtCore.QSize(150, 0))
        self.esam_no_box_2.setText("")
        self.esam_no_box_2.setMaxLength(12)
        self.esam_no_box_2.setObjectName("esam_no_box_2")
        self.horizontalLayout_3.addWidget(self.esam_no_box_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setSpacing(6)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_147 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_147.sizePolicy().hasHeightForWidth())
        self.label_147.setSizePolicy(sizePolicy)
        self.label_147.setMinimumSize(QtCore.QSize(110, 0))
        self.label_147.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_147.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_147.setObjectName("label_147")
        self.horizontalLayout_67.addWidget(self.label_147)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_67.addWidget(self.comboBox_7)
        self.verticalLayout_25.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setSpacing(6)
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_149 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_149.sizePolicy().hasHeightForWidth())
        self.label_149.setSizePolicy(sizePolicy)
        self.label_149.setMinimumSize(QtCore.QSize(110, 0))
        self.label_149.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_149.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_149.setObjectName("label_149")
        self.horizontalLayout_69.addWidget(self.label_149)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_69.addWidget(self.comboBox_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setSpacing(6)
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_148 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_148.sizePolicy().hasHeightForWidth())
        self.label_148.setSizePolicy(sizePolicy)
        self.label_148.setMinimumSize(QtCore.QSize(110, 0))
        self.label_148.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_148.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_148.setObjectName("label_148")
        self.horizontalLayout_68.addWidget(self.label_148)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_68.addWidget(self.comboBox)
        self.verticalLayout_25.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setSpacing(6)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_151 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_151.sizePolicy().hasHeightForWidth())
        self.label_151.setSizePolicy(sizePolicy)
        self.label_151.setMinimumSize(QtCore.QSize(110, 0))
        self.label_151.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_151.setFont(font)
        self.label_151.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_151.setObjectName("label_151")
        self.horizontalLayout_75.addWidget(self.label_151)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.horizontalLayout_75.addWidget(self.comboBox_6)
        self.verticalLayout_25.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setSpacing(6)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_150 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_150.sizePolicy().hasHeightForWidth())
        self.label_150.setSizePolicy(sizePolicy)
        self.label_150.setMinimumSize(QtCore.QSize(110, 0))
        self.label_150.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_150.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_150.setObjectName("label_150")
        self.horizontalLayout_70.addWidget(self.label_150)
        self.esam_dialog_remain_box_2 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_dialog_remain_box_2.sizePolicy().hasHeightForWidth())
        self.esam_dialog_remain_box_2.setSizePolicy(sizePolicy)
        self.esam_dialog_remain_box_2.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_dialog_remain_box_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_dialog_remain_box_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_dialog_remain_box_2.setBaseSize(QtCore.QSize(150, 0))
        self.esam_dialog_remain_box_2.setMaxLength(6)
        self.esam_dialog_remain_box_2.setObjectName("esam_dialog_remain_box_2")
        self.horizontalLayout_70.addWidget(self.esam_dialog_remain_box_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setSpacing(6)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_153 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_153.sizePolicy().hasHeightForWidth())
        self.label_153.setSizePolicy(sizePolicy)
        self.label_153.setMinimumSize(QtCore.QSize(110, 0))
        self.label_153.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_153.setFont(font)
        self.label_153.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_153.setObjectName("label_153")
        self.horizontalLayout_74.addWidget(self.label_153)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_74.addWidget(self.comboBox_5)
        self.verticalLayout_25.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_152 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_152.sizePolicy().hasHeightForWidth())
        self.label_152.setSizePolicy(sizePolicy)
        self.label_152.setMinimumSize(QtCore.QSize(110, 0))
        self.label_152.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_152.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_152.setObjectName("label_152")
        self.horizontalLayout_71.addWidget(self.label_152)
        self.esam_rpt_ctr_box_2 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_rpt_ctr_box_2.sizePolicy().hasHeightForWidth())
        self.esam_rpt_ctr_box_2.setSizePolicy(sizePolicy)
        self.esam_rpt_ctr_box_2.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_rpt_ctr_box_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_rpt_ctr_box_2.setBaseSize(QtCore.QSize(150, 0))
        self.esam_rpt_ctr_box_2.setObjectName("esam_rpt_ctr_box_2")
        self.horizontalLayout_71.addWidget(self.esam_rpt_ctr_box_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setSpacing(6)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_155 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_155.sizePolicy().hasHeightForWidth())
        self.label_155.setSizePolicy(sizePolicy)
        self.label_155.setMinimumSize(QtCore.QSize(110, 0))
        self.label_155.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_155.setFont(font)
        self.label_155.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_155.setObjectName("label_155")
        self.horizontalLayout_73.addWidget(self.label_155)
        self.esam_host_ver_box_2 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_host_ver_box_2.sizePolicy().hasHeightForWidth())
        self.esam_host_ver_box_2.setSizePolicy(sizePolicy)
        self.esam_host_ver_box_2.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_host_ver_box_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_host_ver_box_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_host_ver_box_2.setBaseSize(QtCore.QSize(150, 0))
        self.esam_host_ver_box_2.setObjectName("esam_host_ver_box_2")
        self.horizontalLayout_73.addWidget(self.esam_host_ver_box_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setSpacing(6)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_154 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_154.sizePolicy().hasHeightForWidth())
        self.label_154.setSizePolicy(sizePolicy)
        self.label_154.setMinimumSize(QtCore.QSize(110, 0))
        self.label_154.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_154.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_154.setObjectName("label_154")
        self.horizontalLayout_72.addWidget(self.label_154)
        self.esam_terminal_ver_box_2 = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_terminal_ver_box_2.sizePolicy().hasHeightForWidth())
        self.esam_terminal_ver_box_2.setSizePolicy(sizePolicy)
        self.esam_terminal_ver_box_2.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_terminal_ver_box_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_terminal_ver_box_2.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_terminal_ver_box_2.setBaseSize(QtCore.QSize(150, 0))
        self.esam_terminal_ver_box_2.setObjectName("esam_terminal_ver_box_2")
        self.horizontalLayout_72.addWidget(self.esam_terminal_ver_box_2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_72)
        self.verticalLayout_26.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_11.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_23.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_152 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_152.setSpacing(6)
        self.horizontalLayout_152.setObjectName("horizontalLayout_152")
        self.label_158 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_158.sizePolicy().hasHeightForWidth())
        self.label_158.setSizePolicy(sizePolicy)
        self.label_158.setMinimumSize(QtCore.QSize(110, 0))
        self.label_158.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_158.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_158.setObjectName("label_158")
        self.horizontalLayout_152.addWidget(self.label_158)
        self.esam_ver_box_3 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_ver_box_3.sizePolicy().hasHeightForWidth())
        self.esam_ver_box_3.setSizePolicy(sizePolicy)
        self.esam_ver_box_3.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_ver_box_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_ver_box_3.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_ver_box_3.setBaseSize(QtCore.QSize(150, 0))
        self.esam_ver_box_3.setObjectName("esam_ver_box_3")
        self.horizontalLayout_152.addWidget(self.esam_ver_box_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_152)
        self.horizontalLayout_151 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_151.setSpacing(6)
        self.horizontalLayout_151.setObjectName("horizontalLayout_151")
        self.label_157 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_157.sizePolicy().hasHeightForWidth())
        self.label_157.setSizePolicy(sizePolicy)
        self.label_157.setMinimumSize(QtCore.QSize(110, 0))
        self.label_157.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_157.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_157.setObjectName("label_157")
        self.horizontalLayout_151.addWidget(self.label_157)
        self.esam_no_box_3 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_no_box_3.sizePolicy().hasHeightForWidth())
        self.esam_no_box_3.setSizePolicy(sizePolicy)
        self.esam_no_box_3.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_no_box_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_no_box_3.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_no_box_3.setBaseSize(QtCore.QSize(150, 0))
        self.esam_no_box_3.setObjectName("esam_no_box_3")
        self.horizontalLayout_151.addWidget(self.esam_no_box_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_151)
        self.horizontalLayout_154 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_154.setSpacing(6)
        self.horizontalLayout_154.setObjectName("horizontalLayout_154")
        self.label_160 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_160.sizePolicy().hasHeightForWidth())
        self.label_160.setSizePolicy(sizePolicy)
        self.label_160.setMinimumSize(QtCore.QSize(110, 0))
        self.label_160.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_160.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_160.setObjectName("label_160")
        self.horizontalLayout_154.addWidget(self.label_160)
        self.esam_dialog_tm_box_3 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_dialog_tm_box_3.sizePolicy().hasHeightForWidth())
        self.esam_dialog_tm_box_3.setSizePolicy(sizePolicy)
        self.esam_dialog_tm_box_3.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_dialog_tm_box_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_dialog_tm_box_3.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_dialog_tm_box_3.setBaseSize(QtCore.QSize(150, 0))
        self.esam_dialog_tm_box_3.setObjectName("esam_dialog_tm_box_3")
        self.horizontalLayout_154.addWidget(self.esam_dialog_tm_box_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_154)
        self.horizontalLayout_153 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_153.setSpacing(6)
        self.horizontalLayout_153.setObjectName("horizontalLayout_153")
        self.label_159 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_159.sizePolicy().hasHeightForWidth())
        self.label_159.setSizePolicy(sizePolicy)
        self.label_159.setMinimumSize(QtCore.QSize(110, 0))
        self.label_159.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_159.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_159.setObjectName("label_159")
        self.horizontalLayout_153.addWidget(self.label_159)
        self.esam_key_box_3 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.esam_key_box_3.sizePolicy().hasHeightForWidth())
        self.esam_key_box_3.setSizePolicy(sizePolicy)
        self.esam_key_box_3.setMinimumSize(QtCore.QSize(100, 0))
        self.esam_key_box_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.esam_key_box_3.setSizeIncrement(QtCore.QSize(150, 0))
        self.esam_key_box_3.setBaseSize(QtCore.QSize(150, 0))
        self.esam_key_box_3.setAutoFillBackground(False)
        self.esam_key_box_3.setText("")
        self.esam_key_box_3.setFrame(True)
        self.esam_key_box_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.esam_key_box_3.setDragEnabled(False)
        self.esam_key_box_3.setReadOnly(False)
        self.esam_key_box_3.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.esam_key_box_3.setObjectName("esam_key_box_3")
        self.horizontalLayout_153.addWidget(self.esam_key_box_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_153)
        self.verticalLayout_26.addWidget(self.groupBox_11)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_23.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayout_158 = QtWidgets.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_158.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_158.setSpacing(6)
        self.horizontalLayout_158.setObjectName("horizontalLayout_158")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_157 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_157.setSpacing(6)
        self.horizontalLayout_157.setObjectName("horizontalLayout_157")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_23)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_157.addWidget(self.checkBox)
        self.label_161 = QtWidgets.QLabel(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setBold(False)
        font.setWeight(50)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.horizontalLayout_157.addWidget(self.label_161)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(109, 16777215))
        self.lineEdit_2.setMaxLength(2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_157.addWidget(self.lineEdit_2)
        self.verticalLayout_24.addLayout(self.horizontalLayout_157)
        self.horizontalLayout_156 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_156.setSpacing(6)
        self.horizontalLayout_156.setObjectName("horizontalLayout_156")
        self.esam_r_info_b_2 = QtWidgets.QPushButton(self.groupBox_23)
        self.esam_r_info_b_2.setObjectName("esam_r_info_b_2")
        self.horizontalLayout_156.addWidget(self.esam_r_info_b_2)
        self.esam_r_ctr_b_3 = QtWidgets.QPushButton(self.groupBox_23)
        self.esam_r_ctr_b_3.setEnabled(False)
        self.esam_r_ctr_b_3.setObjectName("esam_r_ctr_b_3")
        self.horizontalLayout_156.addWidget(self.esam_r_ctr_b_3)
        self.verticalLayout_24.addLayout(self.horizontalLayout_156)
        self.label = QtWidgets.QLabel(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_24.addWidget(self.label)
        self.horizontalLayout_158.addLayout(self.verticalLayout_24)
        self.verticalLayout_26.addWidget(self.groupBox_23)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_26)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setMinimumSize(QtCore.QSize(1000, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_28.addWidget(self.tabWidget)
        ParamDreadWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ParamDreadWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(3)
        self.comboBox_2.setCurrentIndex(2)
        self.comboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ParamDreadWindow)

    def retranslateUi(self, ParamDreadWindow):
        _translate = QtCore.QCoreApplication.translate
        ParamDreadWindow.setWindowTitle(_translate("ParamDreadWindow", "参数配置"))
        self.groupBox_10.setTitle(_translate("ParamDreadWindow", "基本信息"))
        self.label_156.setText(_translate("ParamDreadWindow", "配置序号："))
        self.label_146.setText(_translate("ParamDreadWindow", "通讯地址："))
        self.label_147.setText(_translate("ParamDreadWindow", "波特率："))
        self.comboBox_7.setItemText(0, _translate("ParamDreadWindow", "300 bps(0)"))
        self.comboBox_7.setItemText(1, _translate("ParamDreadWindow", "600 bps(1)"))
        self.comboBox_7.setItemText(2, _translate("ParamDreadWindow", "1200 bps(2)"))
        self.comboBox_7.setItemText(3, _translate("ParamDreadWindow", "2400 bps(3)"))
        self.comboBox_7.setItemText(4, _translate("ParamDreadWindow", "4800 bps(4)"))
        self.comboBox_7.setItemText(5, _translate("ParamDreadWindow", "7200 bps(5)"))
        self.comboBox_7.setItemText(6, _translate("ParamDreadWindow", "9600 bps(6)"))
        self.comboBox_7.setItemText(7, _translate("ParamDreadWindow", "19200 bps(7)"))
        self.comboBox_7.setItemText(8, _translate("ParamDreadWindow", "38400 bps(8)"))
        self.comboBox_7.setItemText(9, _translate("ParamDreadWindow", "57600 bps(9)"))
        self.comboBox_7.setItemText(10, _translate("ParamDreadWindow", "115200 bps(10)"))
        self.comboBox_7.setItemText(11, _translate("ParamDreadWindow", "自适应 (255)"))
        self.label_149.setText(_translate("ParamDreadWindow", "通讯端口："))
        self.comboBox_2.setItemText(0, _translate("ParamDreadWindow", "485-1"))
        self.comboBox_2.setItemText(1, _translate("ParamDreadWindow", "485-2"))
        self.comboBox_2.setItemText(2, _translate("ParamDreadWindow", "PLC"))
        self.label_148.setText(_translate("ParamDreadWindow", "规约类型："))
        self.comboBox.setItemText(0, _translate("ParamDreadWindow", "未知(0)"))
        self.comboBox.setItemText(1, _translate("ParamDreadWindow", "DL/T645-1997(1)"))
        self.comboBox.setItemText(2, _translate("ParamDreadWindow", "DL/T645-2007(2)"))
        self.comboBox.setItemText(3, _translate("ParamDreadWindow", "DL/T698.45(3)"))
        self.comboBox.setItemText(4, _translate("ParamDreadWindow", "CJ/T 188-2004(4)"))
        self.label_151.setText(_translate("ParamDreadWindow", "费率个数："))
        self.comboBox_6.setItemText(0, _translate("ParamDreadWindow", "4"))
        self.label_150.setText(_translate("ParamDreadWindow", "通信密码："))
        self.esam_dialog_remain_box_2.setText(_translate("ParamDreadWindow", "000000"))
        self.label_153.setText(_translate("ParamDreadWindow", "接线方式："))
        self.comboBox_5.setItemText(0, _translate("ParamDreadWindow", "三相四线"))
        self.comboBox_5.setItemText(1, _translate("ParamDreadWindow", "三相三线"))
        self.comboBox_5.setItemText(2, _translate("ParamDreadWindow", "单相"))
        self.label_152.setText(_translate("ParamDreadWindow", "用户类型："))
        self.label_155.setText(_translate("ParamDreadWindow", "额定电流："))
        self.label_154.setText(_translate("ParamDreadWindow", "额定电压："))
        self.groupBox_11.setTitle(_translate("ParamDreadWindow", "扩展信息"))
        self.label_158.setText(_translate("ParamDreadWindow", "资产号："))
        self.label_157.setText(_translate("ParamDreadWindow", "采集器地址："))
        self.label_160.setText(_translate("ParamDreadWindow", "PT："))
        self.label_159.setText(_translate("ParamDreadWindow", "CT："))
        self.checkBox.setText(_translate("ParamDreadWindow", "批量增加"))
        self.label_161.setText(_translate("ParamDreadWindow", "批量增加数量："))
        self.esam_r_info_b_2.setText(_translate("ParamDreadWindow", "读取档案"))
        self.esam_r_ctr_b_3.setText(_translate("ParamDreadWindow", "设置档案"))
        self.label.setText(_translate("ParamDreadWindow", "操作结果："))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ParamDreadWindow", "配置序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ParamDreadWindow", "波特率"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ParamDreadWindow", "通讯端口"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ParamDreadWindow", "规约类型"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ParamDreadWindow", "费率个数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ParamDreadWindow", "接线方式"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ParamDreadWindow", "用户类型"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ParamDreadWindow", "额定电流"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ParamDreadWindow", "额定电压"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("ParamDreadWindow", "采集档案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ParamDreadWindow", "方案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ParamDreadWindow", "任务"))
# import icon_rc
