# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\param_dread_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParamDreadWindow(object):
    def setupUi(self, ParamDreadWindow):
        ParamDreadWindow.setObjectName("ParamDreadWindow")
        ParamDreadWindow.resize(1395, 784)
        self.centralwidget = QtWidgets.QWidget(ParamDreadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_meter = QtWidgets.QWidget()
        self.tab_meter.setObjectName("tab_meter")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_meter)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Basic_object = QtWidgets.QGroupBox(self.tab_meter)
        self.groupBox_Basic_object.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_Basic_object.setObjectName("groupBox_Basic_object")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_Basic_object)
        self.verticalLayout_25.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_155 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_155.setSpacing(6)
        self.horizontalLayout_155.setObjectName("horizontalLayout_155")
        self.label_cfg_no = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cfg_no.sizePolicy().hasHeightForWidth())
        self.label_cfg_no.setSizePolicy(sizePolicy)
        self.label_cfg_no.setMinimumSize(QtCore.QSize(110, 0))
        self.label_cfg_no.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_cfg_no.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cfg_no.setObjectName("label_cfg_no")
        self.horizontalLayout_155.addWidget(self.label_cfg_no)
        self.lineEdit_cfg_no = QtWidgets.QLineEdit(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cfg_no.sizePolicy().hasHeightForWidth())
        self.lineEdit_cfg_no.setSizePolicy(sizePolicy)
        self.lineEdit_cfg_no.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_cfg_no.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_cfg_no.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_cfg_no.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_cfg_no.setMaxLength(4)
        self.lineEdit_cfg_no.setObjectName("lineEdit_cfg_no")
        self.horizontalLayout_155.addWidget(self.lineEdit_cfg_no)
        self.verticalLayout_25.addLayout(self.horizontalLayout_155)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_maddr = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_maddr.sizePolicy().hasHeightForWidth())
        self.label_maddr.setSizePolicy(sizePolicy)
        self.label_maddr.setMinimumSize(QtCore.QSize(110, 0))
        self.label_maddr.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_maddr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_maddr.setObjectName("label_maddr")
        self.horizontalLayout_3.addWidget(self.label_maddr)
        self.lineEdit_maddr = QtWidgets.QLineEdit(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_maddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_maddr.setSizePolicy(sizePolicy)
        self.lineEdit_maddr.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_maddr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_maddr.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_maddr.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_maddr.setMaxLength(12)
        self.lineEdit_maddr.setObjectName("lineEdit_maddr")
        self.horizontalLayout_3.addWidget(self.lineEdit_maddr)
        self.verticalLayout_25.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setSpacing(6)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_baudrate = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_baudrate.sizePolicy().hasHeightForWidth())
        self.label_baudrate.setSizePolicy(sizePolicy)
        self.label_baudrate.setMinimumSize(QtCore.QSize(110, 0))
        self.label_baudrate.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_baudrate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_baudrate.setObjectName("label_baudrate")
        self.horizontalLayout_67.addWidget(self.label_baudrate)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.horizontalLayout_67.addWidget(self.comboBox_baudrate)
        self.verticalLayout_25.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setSpacing(6)
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_port = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_port.sizePolicy().hasHeightForWidth())
        self.label_port.setSizePolicy(sizePolicy)
        self.label_port.setMinimumSize(QtCore.QSize(110, 0))
        self.label_port.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_port.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_port.setObjectName("label_port")
        self.horizontalLayout_69.addWidget(self.label_port)
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_port.setObjectName("comboBox_port")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.horizontalLayout_69.addWidget(self.comboBox_port)
        self.verticalLayout_25.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setSpacing(6)
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_ptl = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ptl.sizePolicy().hasHeightForWidth())
        self.label_ptl.setSizePolicy(sizePolicy)
        self.label_ptl.setMinimumSize(QtCore.QSize(110, 0))
        self.label_ptl.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_ptl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ptl.setObjectName("label_ptl")
        self.horizontalLayout_68.addWidget(self.label_ptl)
        self.comboBox_ptl = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_ptl.setObjectName("comboBox_ptl")
        self.comboBox_ptl.addItem("")
        self.comboBox_ptl.addItem("")
        self.comboBox_ptl.addItem("")
        self.comboBox_ptl.addItem("")
        self.comboBox_ptl.addItem("")
        self.horizontalLayout_68.addWidget(self.comboBox_ptl)
        self.verticalLayout_25.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setSpacing(6)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_rate = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rate.sizePolicy().hasHeightForWidth())
        self.label_rate.setSizePolicy(sizePolicy)
        self.label_rate.setMinimumSize(QtCore.QSize(110, 0))
        self.label_rate.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.label_rate.setFont(font)
        self.label_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rate.setObjectName("label_rate")
        self.horizontalLayout_75.addWidget(self.label_rate)
        self.comboBox_rate = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_rate.setEditable(True)
        self.comboBox_rate.setMaxCount(8)
        self.comboBox_rate.setObjectName("comboBox_rate")
        self.comboBox_rate.addItem("")
        self.horizontalLayout_75.addWidget(self.comboBox_rate)
        self.verticalLayout_25.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setSpacing(6)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_pwd = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pwd.sizePolicy().hasHeightForWidth())
        self.label_pwd.setSizePolicy(sizePolicy)
        self.label_pwd.setMinimumSize(QtCore.QSize(110, 0))
        self.label_pwd.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_pwd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pwd.setObjectName("label_pwd")
        self.horizontalLayout_70.addWidget(self.label_pwd)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pwd.sizePolicy().hasHeightForWidth())
        self.lineEdit_pwd.setSizePolicy(sizePolicy)
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_pwd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_pwd.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_pwd.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_pwd.setMaxLength(12)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.horizontalLayout_70.addWidget(self.lineEdit_pwd)
        self.verticalLayout_25.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setSpacing(6)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_lineMode = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lineMode.sizePolicy().hasHeightForWidth())
        self.label_lineMode.setSizePolicy(sizePolicy)
        self.label_lineMode.setMinimumSize(QtCore.QSize(110, 0))
        self.label_lineMode.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_lineMode.setFont(font)
        self.label_lineMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_lineMode.setObjectName("label_lineMode")
        self.horizontalLayout_74.addWidget(self.label_lineMode)
        self.comboBox_lineMode = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_lineMode.setObjectName("comboBox_lineMode")
        self.comboBox_lineMode.addItem("")
        self.comboBox_lineMode.addItem("")
        self.comboBox_lineMode.addItem("")
        self.comboBox_lineMode.addItem("")
        self.horizontalLayout_74.addWidget(self.comboBox_lineMode)
        self.verticalLayout_25.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_usrType = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_usrType.sizePolicy().hasHeightForWidth())
        self.label_usrType.setSizePolicy(sizePolicy)
        self.label_usrType.setMinimumSize(QtCore.QSize(110, 0))
        self.label_usrType.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_usrType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_usrType.setObjectName("label_usrType")
        self.horizontalLayout_71.addWidget(self.label_usrType)
        self.comboBox_usrType = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_usrType.setEditable(True)
        self.comboBox_usrType.setObjectName("comboBox_usrType")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.comboBox_usrType.addItem("")
        self.horizontalLayout_71.addWidget(self.comboBox_usrType)
        self.verticalLayout_25.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setSpacing(6)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_stdV = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stdV.sizePolicy().hasHeightForWidth())
        self.label_stdV.setSizePolicy(sizePolicy)
        self.label_stdV.setMinimumSize(QtCore.QSize(110, 0))
        self.label_stdV.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_stdV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stdV.setObjectName("label_stdV")
        self.horizontalLayout_72.addWidget(self.label_stdV)
        self.comboBox_stdV = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_stdV.setEditable(True)
        self.comboBox_stdV.setObjectName("comboBox_stdV")
        self.comboBox_stdV.addItem("")
        self.comboBox_stdV.addItem("")
        self.horizontalLayout_72.addWidget(self.comboBox_stdV)
        self.verticalLayout_25.addLayout(self.horizontalLayout_72)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setSpacing(6)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_stdA = QtWidgets.QLabel(self.groupBox_Basic_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stdA.sizePolicy().hasHeightForWidth())
        self.label_stdA.setSizePolicy(sizePolicy)
        self.label_stdA.setMinimumSize(QtCore.QSize(110, 0))
        self.label_stdA.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_stdA.setFont(font)
        self.label_stdA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_stdA.setObjectName("label_stdA")
        self.horizontalLayout_73.addWidget(self.label_stdA)
        self.comboBox_stdA = QtWidgets.QComboBox(self.groupBox_Basic_object)
        self.comboBox_stdA.setEditable(True)
        self.comboBox_stdA.setObjectName("comboBox_stdA")
        self.comboBox_stdA.addItem("")
        self.comboBox_stdA.addItem("")
        self.horizontalLayout_73.addWidget(self.comboBox_stdA)
        self.verticalLayout_25.addLayout(self.horizontalLayout_73)
        self.verticalLayout.addWidget(self.groupBox_Basic_object)
        self.groupBox_Extended_object = QtWidgets.QGroupBox(self.tab_meter)
        self.groupBox_Extended_object.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_Extended_object.setObjectName("groupBox_Extended_object")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_Extended_object)
        self.verticalLayout_23.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_152 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_152.setSpacing(6)
        self.horizontalLayout_152.setObjectName("horizontalLayout_152")
        self.label_assetNumber = QtWidgets.QLabel(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_assetNumber.sizePolicy().hasHeightForWidth())
        self.label_assetNumber.setSizePolicy(sizePolicy)
        self.label_assetNumber.setMinimumSize(QtCore.QSize(110, 0))
        self.label_assetNumber.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_assetNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_assetNumber.setObjectName("label_assetNumber")
        self.horizontalLayout_152.addWidget(self.label_assetNumber)
        self.lineEdit_assetNumber = QtWidgets.QLineEdit(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_assetNumber.sizePolicy().hasHeightForWidth())
        self.lineEdit_assetNumber.setSizePolicy(sizePolicy)
        self.lineEdit_assetNumber.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_assetNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_assetNumber.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_assetNumber.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_assetNumber.setMaxLength(12)
        self.lineEdit_assetNumber.setObjectName("lineEdit_assetNumber")
        self.horizontalLayout_152.addWidget(self.lineEdit_assetNumber)
        self.verticalLayout_23.addLayout(self.horizontalLayout_152)
        self.horizontalLayout_151 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_151.setSpacing(6)
        self.horizontalLayout_151.setObjectName("horizontalLayout_151")
        self.label_collAddr = QtWidgets.QLabel(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_collAddr.sizePolicy().hasHeightForWidth())
        self.label_collAddr.setSizePolicy(sizePolicy)
        self.label_collAddr.setMinimumSize(QtCore.QSize(110, 0))
        self.label_collAddr.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_collAddr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_collAddr.setObjectName("label_collAddr")
        self.horizontalLayout_151.addWidget(self.label_collAddr)
        self.lineEdit_collAddr = QtWidgets.QLineEdit(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_collAddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_collAddr.setSizePolicy(sizePolicy)
        self.lineEdit_collAddr.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_collAddr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_collAddr.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_collAddr.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_collAddr.setMaxLength(12)
        self.lineEdit_collAddr.setObjectName("lineEdit_collAddr")
        self.horizontalLayout_151.addWidget(self.lineEdit_collAddr)
        self.verticalLayout_23.addLayout(self.horizontalLayout_151)
        self.horizontalLayout_154 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_154.setSpacing(6)
        self.horizontalLayout_154.setObjectName("horizontalLayout_154")
        self.label_PT = QtWidgets.QLabel(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PT.sizePolicy().hasHeightForWidth())
        self.label_PT.setSizePolicy(sizePolicy)
        self.label_PT.setMinimumSize(QtCore.QSize(110, 0))
        self.label_PT.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_PT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_PT.setObjectName("label_PT")
        self.horizontalLayout_154.addWidget(self.label_PT)
        self.lineEdit_PT = QtWidgets.QLineEdit(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PT.sizePolicy().hasHeightForWidth())
        self.lineEdit_PT.setSizePolicy(sizePolicy)
        self.lineEdit_PT.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_PT.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_PT.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_PT.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_PT.setMaxLength(3)
        self.lineEdit_PT.setObjectName("lineEdit_PT")
        self.horizontalLayout_154.addWidget(self.lineEdit_PT)
        self.verticalLayout_23.addLayout(self.horizontalLayout_154)
        self.horizontalLayout_153 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_153.setSpacing(6)
        self.horizontalLayout_153.setObjectName("horizontalLayout_153")
        self.label_CT = QtWidgets.QLabel(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CT.sizePolicy().hasHeightForWidth())
        self.label_CT.setSizePolicy(sizePolicy)
        self.label_CT.setMinimumSize(QtCore.QSize(110, 0))
        self.label_CT.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_CT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CT.setObjectName("label_CT")
        self.horizontalLayout_153.addWidget(self.label_CT)
        self.lineEdit_CT = QtWidgets.QLineEdit(self.groupBox_Extended_object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CT.sizePolicy().hasHeightForWidth())
        self.lineEdit_CT.setSizePolicy(sizePolicy)
        self.lineEdit_CT.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_CT.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_CT.setSizeIncrement(QtCore.QSize(150, 0))
        self.lineEdit_CT.setBaseSize(QtCore.QSize(150, 0))
        self.lineEdit_CT.setAutoFillBackground(False)
        self.lineEdit_CT.setMaxLength(3)
        self.lineEdit_CT.setFrame(True)
        self.lineEdit_CT.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_CT.setDragEnabled(False)
        self.lineEdit_CT.setReadOnly(False)
        self.lineEdit_CT.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_CT.setObjectName("lineEdit_CT")
        self.horizontalLayout_153.addWidget(self.lineEdit_CT)
        self.verticalLayout_23.addLayout(self.horizontalLayout_153)
        self.verticalLayout.addWidget(self.groupBox_Extended_object)
        self.groupBox_param = QtWidgets.QGroupBox(self.tab_meter)
        self.groupBox_param.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_param.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_param.setTitle("")
        self.groupBox_param.setObjectName("groupBox_param")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_param)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox_param)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_batchAdd = QtWidgets.QLineEdit(self.groupBox_param)
        self.lineEdit_batchAdd.setEnabled(True)
        self.lineEdit_batchAdd.setMaximumSize(QtCore.QSize(98, 16777215))
        self.lineEdit_batchAdd.setMaxLength(4)
        self.lineEdit_batchAdd.setObjectName("lineEdit_batchAdd")
        self.horizontalLayout.addWidget(self.lineEdit_batchAdd)
        self.PushButton_batchAdd = QtWidgets.QPushButton(self.groupBox_param)
        self.PushButton_batchAdd.setObjectName("PushButton_batchAdd")
        self.horizontalLayout.addWidget(self.PushButton_batchAdd)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_param)
        self.label_status = QtWidgets.QLabel(self.tab_meter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PushButton_set = QtWidgets.QPushButton(self.tab_meter)
        self.PushButton_set.setMinimumSize(QtCore.QSize(50, 0))
        self.PushButton_set.setObjectName("PushButton_set")
        self.horizontalLayout_2.addWidget(self.PushButton_set)
        self.PushButton_get = QtWidgets.QPushButton(self.tab_meter)
        self.PushButton_get.setEnabled(True)
        self.PushButton_get.setMinimumSize(QtCore.QSize(50, 0))
        self.PushButton_get.setObjectName("PushButton_get")
        self.horizontalLayout_2.addWidget(self.PushButton_get)
        self.PushButton_stop = QtWidgets.QPushButton(self.tab_meter)
        self.PushButton_stop.setEnabled(True)
        self.PushButton_stop.setMinimumSize(QtCore.QSize(50, 0))
        self.PushButton_stop.setObjectName("PushButton_stop")
        self.horizontalLayout_2.addWidget(self.PushButton_stop)
        self.PushButton_import = QtWidgets.QPushButton(self.tab_meter)
        self.PushButton_import.setEnabled(True)
        self.PushButton_import.setMinimumSize(QtCore.QSize(50, 0))
        self.PushButton_import.setObjectName("PushButton_import")
        self.horizontalLayout_2.addWidget(self.PushButton_import)
        self.PushButton_clear = QtWidgets.QPushButton(self.tab_meter)
        self.PushButton_clear.setEnabled(True)
        self.PushButton_clear.setMinimumSize(QtCore.QSize(50, 0))
        self.PushButton_clear.setObjectName("PushButton_clear")
        self.horizontalLayout_2.addWidget(self.PushButton_clear)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_cnt = QtWidgets.QLabel(self.tab_meter)
        self.label_cnt.setObjectName("label_cnt")
        self.horizontalLayout_4.addWidget(self.label_cnt)
        self.lineEdit_cnt = QtWidgets.QLineEdit(self.tab_meter)
        self.lineEdit_cnt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_cnt.setMaxLength(3)
        self.lineEdit_cnt.setObjectName("lineEdit_cnt")
        self.horizontalLayout_4.addWidget(self.lineEdit_cnt)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_delay = QtWidgets.QLabel(self.tab_meter)
        self.label_delay.setObjectName("label_delay")
        self.horizontalLayout_5.addWidget(self.label_delay)
        self.lineEdit_delay = QtWidgets.QLineEdit(self.tab_meter)
        self.lineEdit_delay.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_delay.setMaxLength(5)
        self.lineEdit_delay.setObjectName("lineEdit_delay")
        self.horizontalLayout_5.addWidget(self.lineEdit_delay)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.progressBar = QtWidgets.QProgressBar(self.tab_meter)
        self.progressBar.setMinimumSize(QtCore.QSize(300, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_meter)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(1150, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAccessibleName("")
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_meter, "")
        self.tab_scheme = QtWidgets.QWidget()
        self.tab_scheme.setObjectName("tab_scheme")
        self.tabWidget.addTab(self.tab_scheme, "")
        self.tab_task = QtWidgets.QWidget()
        self.tab_task.setObjectName("tab_task")
        self.tabWidget.addTab(self.tab_task, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        ParamDreadWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ParamDreadWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_baudrate.setCurrentIndex(3)
        self.comboBox_port.setCurrentIndex(0)
        self.comboBox_ptl.setCurrentIndex(2)
        self.comboBox_lineMode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ParamDreadWindow)

    def retranslateUi(self, ParamDreadWindow):
        _translate = QtCore.QCoreApplication.translate
        ParamDreadWindow.setWindowTitle(_translate("ParamDreadWindow", "抄表配置"))
        self.groupBox_Basic_object.setTitle(_translate("ParamDreadWindow", "基本信息"))
        self.label_cfg_no.setText(_translate("ParamDreadWindow", "配置序号："))
        self.lineEdit_cfg_no.setText(_translate("ParamDreadWindow", "2"))
        self.label_maddr.setText(_translate("ParamDreadWindow", "通信地址："))
        self.lineEdit_maddr.setText(_translate("ParamDreadWindow", "000000000002"))
        self.label_baudrate.setText(_translate("ParamDreadWindow", "波特率："))
        self.comboBox_baudrate.setItemText(0, _translate("ParamDreadWindow", "300 bps(0)"))
        self.comboBox_baudrate.setItemText(1, _translate("ParamDreadWindow", "600 bps(1)"))
        self.comboBox_baudrate.setItemText(2, _translate("ParamDreadWindow", "1200 bps(2)"))
        self.comboBox_baudrate.setItemText(3, _translate("ParamDreadWindow", "2400 bps(3)"))
        self.comboBox_baudrate.setItemText(4, _translate("ParamDreadWindow", "4800 bps(4)"))
        self.comboBox_baudrate.setItemText(5, _translate("ParamDreadWindow", "7200 bps(5)"))
        self.comboBox_baudrate.setItemText(6, _translate("ParamDreadWindow", "9600 bps(6)"))
        self.comboBox_baudrate.setItemText(7, _translate("ParamDreadWindow", "19200 bps(7)"))
        self.comboBox_baudrate.setItemText(8, _translate("ParamDreadWindow", "38400 bps(8)"))
        self.comboBox_baudrate.setItemText(9, _translate("ParamDreadWindow", "57600 bps(9)"))
        self.comboBox_baudrate.setItemText(10, _translate("ParamDreadWindow", "115200 bps(10)"))
        self.comboBox_baudrate.setItemText(11, _translate("ParamDreadWindow", "自适应 (255)"))
        self.label_port.setText(_translate("ParamDreadWindow", "通信端口："))
        self.comboBox_port.setItemText(0, _translate("ParamDreadWindow", "485-1(F2010201)"))
        self.comboBox_port.setItemText(1, _translate("ParamDreadWindow", "485-2(F2010202)"))
        self.comboBox_port.setItemText(2, _translate("ParamDreadWindow", "485-3(F2010203)"))
        self.comboBox_port.setItemText(3, _translate("ParamDreadWindow", "PLC(F2090201)"))
        self.comboBox_port.setItemText(4, _translate("ParamDreadWindow", "交采(F2080201)"))
        self.comboBox_port.setItemText(5, _translate("ParamDreadWindow", "无效"))
        self.label_ptl.setText(_translate("ParamDreadWindow", "规约类型："))
        self.comboBox_ptl.setItemText(0, _translate("ParamDreadWindow", "未知(0)"))
        self.comboBox_ptl.setItemText(1, _translate("ParamDreadWindow", "DL/T645-1997(1)"))
        self.comboBox_ptl.setItemText(2, _translate("ParamDreadWindow", "DL/T645-2007(2)"))
        self.comboBox_ptl.setItemText(3, _translate("ParamDreadWindow", "DL/T698.45(3)"))
        self.comboBox_ptl.setItemText(4, _translate("ParamDreadWindow", "CJ/T 188-2004(4)"))
        self.label_rate.setText(_translate("ParamDreadWindow", "费率个数："))
        self.comboBox_rate.setItemText(0, _translate("ParamDreadWindow", "4"))
        self.label_pwd.setText(_translate("ParamDreadWindow", "通信密码："))
        self.lineEdit_pwd.setText(_translate("ParamDreadWindow", "000000000000"))
        self.label_lineMode.setText(_translate("ParamDreadWindow", "接线方式："))
        self.comboBox_lineMode.setItemText(0, _translate("ParamDreadWindow", "未知(0)"))
        self.comboBox_lineMode.setItemText(1, _translate("ParamDreadWindow", "单相(1)"))
        self.comboBox_lineMode.setItemText(2, _translate("ParamDreadWindow", "三相三线(2)"))
        self.comboBox_lineMode.setItemText(3, _translate("ParamDreadWindow", "三相四线(3)"))
        self.label_usrType.setText(_translate("ParamDreadWindow", "用户类型："))
        self.comboBox_usrType.setItemText(0, _translate("ParamDreadWindow", "0"))
        self.comboBox_usrType.setItemText(1, _translate("ParamDreadWindow", "1"))
        self.comboBox_usrType.setItemText(2, _translate("ParamDreadWindow", "2"))
        self.comboBox_usrType.setItemText(3, _translate("ParamDreadWindow", "3"))
        self.comboBox_usrType.setItemText(4, _translate("ParamDreadWindow", "4"))
        self.comboBox_usrType.setItemText(5, _translate("ParamDreadWindow", "5"))
        self.comboBox_usrType.setItemText(6, _translate("ParamDreadWindow", "6"))
        self.comboBox_usrType.setItemText(7, _translate("ParamDreadWindow", "7"))
        self.comboBox_usrType.setItemText(8, _translate("ParamDreadWindow", "8"))
        self.comboBox_usrType.setItemText(9, _translate("ParamDreadWindow", "9"))
        self.label_stdV.setText(_translate("ParamDreadWindow", "额定电压(V)："))
        self.comboBox_stdV.setItemText(0, _translate("ParamDreadWindow", "220"))
        self.comboBox_stdV.setItemText(1, _translate("ParamDreadWindow", "100"))
        self.label_stdA.setText(_translate("ParamDreadWindow", "额定电流(A)："))
        self.comboBox_stdA.setItemText(0, _translate("ParamDreadWindow", "1.5"))
        self.comboBox_stdA.setItemText(1, _translate("ParamDreadWindow", "5"))
        self.groupBox_Extended_object.setTitle(_translate("ParamDreadWindow", "扩展信息"))
        self.label_assetNumber.setText(_translate("ParamDreadWindow", "资产号："))
        self.lineEdit_assetNumber.setText(_translate("ParamDreadWindow", "000000000000"))
        self.label_collAddr.setText(_translate("ParamDreadWindow", "采集器地址："))
        self.lineEdit_collAddr.setText(_translate("ParamDreadWindow", "000000000000"))
        self.label_PT.setText(_translate("ParamDreadWindow", "PT："))
        self.lineEdit_PT.setText(_translate("ParamDreadWindow", "1"))
        self.label_CT.setText(_translate("ParamDreadWindow", "CT："))
        self.lineEdit_CT.setText(_translate("ParamDreadWindow", "1"))
        self.label.setText(_translate("ParamDreadWindow", "数量："))
        self.lineEdit_batchAdd.setText(_translate("ParamDreadWindow", "1"))
        self.PushButton_batchAdd.setText(_translate("ParamDreadWindow", "增加->"))
        self.PushButton_set.setText(_translate("ParamDreadWindow", "下发"))
        self.PushButton_get.setText(_translate("ParamDreadWindow", "读取"))
        self.PushButton_stop.setText(_translate("ParamDreadWindow", "终止"))
        self.PushButton_import.setText(_translate("ParamDreadWindow", "导入"))
        self.PushButton_clear.setText(_translate("ParamDreadWindow", "清空"))
        self.label_cnt.setText(_translate("ParamDreadWindow", "    每包下发数量："))
        self.lineEdit_cnt.setText(_translate("ParamDreadWindow", "20"))
        self.label_delay.setText(_translate("ParamDreadWindow", "每包下发延时(ms)："))
        self.lineEdit_delay.setText(_translate("ParamDreadWindow", "1000"))
        self.tableWidget.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_meter), _translate("ParamDreadWindow", "采集档案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scheme), _translate("ParamDreadWindow", "方案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_task), _translate("ParamDreadWindow", "任务"))
# import icon_rc
